/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gaumanagementsystem.view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.GridLayout;

/**
 *
 * @author wangel
 */
public class EditProfileView extends javax.swing.JFrame {

    // Calendar button for date of birth
    private JButton calendarButton;

    /**
     * Creates new form EditProfileView
     */
    public EditProfileView() {
        initComponents();
        ButtonGroup gender = new ButtonGroup();
        gender.add(male);
        gender.add(female);
        
        // Make date field clickable for calendar
        setupDateFieldCalendar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        father_name = new javax.swing.JTextField();
        mother_name = new javax.swing.JTextField();
        citizen_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        upload = new javax.swing.JButton();
        ProfileImageLabel = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        backtoprofile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Hamro Smart Gaun");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 12, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 387, -1, -1));

        female.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 385, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Phone");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 422, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Mother's Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 492, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Father's Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 457, -1, -1));

        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Ward");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 528, -1, -1));

        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 247, 300, -1));

        address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 350, 300, -1));

        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 315, 300, -1));

        father_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(father_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 454, 300, -1));

        mother_name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mother_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mother_nameActionPerformed(evt);
            }
        });
        getContentPane().add(mother_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 489, 300, -1));

        citizen_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(citizen_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 212, 300, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Citizenship Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 215, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        dateofbirth.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateofbirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateofbirthActionPerformed(evt);
            }
        });
        getContentPane().add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 282, 300, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 318, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Date of Birth");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 285, -1, -1));

        phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 419, 300, -1));

        ward = new javax.swing.JTextField();
        ward.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(ward, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 525, 300, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 353, -1, -1));

        male.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 385, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        upload.setBackground(new java.awt.Color(102, 102, 255));
        upload.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        upload.setForeground(new java.awt.Color(255, 255, 255));
        upload.setText("Upload Picture");

        ProfileImageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        save.setBackground(new java.awt.Color(102, 102, 255));
        save.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        backtoprofile.setBackground(new java.awt.Color(102, 102, 255));
        backtoprofile.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backtoprofile.setForeground(new java.awt.Color(255, 255, 255));
        backtoprofile.setText("Back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ProfileImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(upload))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(backtoprofile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ProfileImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(upload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backtoprofile)
                    .addComponent(save))
                .addGap(79, 79, 79))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 620, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void mother_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mother_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mother_nameActionPerformed

    private void dateofbirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateofbirthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateofbirthActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfileView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProfileView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProfileImageLabel;
    private javax.swing.JTextField address;
    private javax.swing.JButton backtoprofile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField citizen_id;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JTextField email;
    private javax.swing.JTextField father_name;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mother_name;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField ward;
    private javax.swing.JButton save;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getCitizenIdField() {
        return citizen_id;
    }

    public javax.swing.JTextField getNameField() {
        return name;
    }
    
    public javax.swing.JTextField getDateOfBirthField() {
    return dateofbirth;
    }

    public javax.swing.JTextField getEmailField() {
        return email;
    }

    public javax.swing.JTextField getAddressField() {
        return address;
    }

    public String getRadioButton() {
        if (male.isSelected()) {
           return "Male";
        } else {
            return "Female";
    }
    }
    
    public javax.swing.JTextField getPhoneField() {
        return phone;
    }

    public javax.swing.JTextField getFatherNameField() {
        return father_name;
    }

    public javax.swing.JTextField getMotherNameField() {
        return mother_name;
    }

    public javax.swing.JTextField getWardField() {
        return ward;
    }

    public javax.swing.JButton getEditButton() {
        return save;
    }

    public javax.swing.JButton getBackButton() {
        return backtoprofile;
    }

    public javax.swing.JLabel getProfileImageLabel() {
        return ProfileImageLabel;
    }

    public javax.swing.JButton getUploadButton() {
        return upload;
    }

    private String selectedImagePath = null; // To store the uploaded image path
    private String role = "admin";
    private String userCitizenId = null;
    private boolean isEditMode = false;

    public EditProfileView(String role, String citizenId, boolean isEditMode) {
        this();
        this.role = role;
        this.userCitizenId = citizenId;
        this.isEditMode = isEditMode;
        // Role-based button visibility
        if ("admin".equalsIgnoreCase(role)) {
            save.setVisible(true);
            backtoprofile.setVisible(true);
        } else if ("user".equalsIgnoreCase(role)) {
            save.setVisible(true);
            backtoprofile.setVisible(true);
        }
        // Data loading logic
        if (isEditMode && citizenId != null) {
            gaumanagementsystem.controller.CitizenController controller = new gaumanagementsystem.controller.CitizenController();
            gaumanagementsystem.model.CitizenData citizen = controller.getCitizenById(citizenId);
            if (citizen != null) {
                citizen_id.setText(citizen.getCitizenId());
                name.setText(citizen.getName());
                email.setText(citizen.getEmail());
                dateofbirth.setText(citizen.getDateOfBirth());
                address.setText(citizen.getAddress());
                phone.setText(citizen.getPhone());
                father_name.setText(citizen.getFatherName());
                mother_name.setText(citizen.getMotherName());
                ward.setText(String.valueOf(citizen.getWard()));
                if ("Male".equalsIgnoreCase(citizen.getGender())) {
                    male.setSelected(true);
                } else if ("Female".equalsIgnoreCase(citizen.getGender())) {
                    female.setSelected(true);
                } else {
                    buttonGroup1.clearSelection();
                }
                // Load image if available
                if (citizen.getImagePath() != null && !citizen.getImagePath().isEmpty()) {
                    javax.swing.ImageIcon originalIcon = new javax.swing.ImageIcon(citizen.getImagePath());
                    java.awt.Image scaledImage = originalIcon.getImage().getScaledInstance(90, 90, java.awt.Image.SCALE_SMOOTH);
                    ProfileImageLabel.setIcon(new javax.swing.ImageIcon(scaledImage));
                    selectedImagePath = citizen.getImagePath();
                }
            }
        } else {
            citizen_id.setText("");
            name.setText("");
            email.setText("");
            dateofbirth.setText("");
            address.setText("");
            phone.setText("");
            father_name.setText("");
            mother_name.setText("");
            ward.setText("");
            buttonGroup1.clearSelection();
            ProfileImageLabel.setIcon(null);
            selectedImagePath = null;
        }
        // Add action listeners for buttons
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        backtoprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoprofileActionPerformed(evt);
            }
        });
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
    }

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {
        // Gather data from fields
        String id = citizen_id.getText().trim();
        String nm = name.getText().trim();
        String em = email.getText().trim();
        String dob = dateofbirth.getText().trim();
        String addr = address.getText().trim();
        String ph = phone.getText().trim();
        String fn = father_name.getText().trim();
        String mn = mother_name.getText().trim();
        String gender = male.isSelected() ? "Male" : (female.isSelected() ? "Female" : "");
        String imgPath = selectedImagePath;
        
        // Parse ward from text field, default to 1 if invalid
        int wardNumber = 1;
        try {
            String wardText = ward.getText().trim();
            if (!wardText.isEmpty()) {
                wardNumber = Integer.parseInt(wardText);
            }
        } catch (NumberFormatException e) {
            wardNumber = 1; // Default to ward 1 if parsing fails
        }
        
        gaumanagementsystem.model.CitizenData citizen = new gaumanagementsystem.model.CitizenData(id, nm, em, dob, addr, gender, ph, fn, mn, imgPath, wardNumber);
        gaumanagementsystem.controller.CitizenController controller = new gaumanagementsystem.controller.CitizenController();
        boolean success;
        if (isEditMode) {
            success = controller.updateCitizen(citizen);
        } else {
            success = controller.createCitizen(citizen);
        }
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, "Citizen saved successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Handle role-based navigation after saving
            if ("user".equalsIgnoreCase(role)) {
                // For user role, open their profile view to show the saved data
                gaumanagementsystem.view.ProfileView profileView = 
                    new gaumanagementsystem.view.ProfileView(id, true, role);
                profileView.setVisible(true);
                this.dispose();
            } else {
                // For admin role, return to CitizenEdit
                new CitizenEdit(role, id).setVisible(true);
                this.dispose();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to save citizen. Please check your inputs.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void backtoprofileActionPerformed(java.awt.event.ActionEvent evt) {
        // Handle role-based navigation for back button
        if ("user".equalsIgnoreCase(role)) {
            // For user role, go back to dashboard with their user ID
            gaumanagementsystem.view.DashboardView dashboard = 
                new gaumanagementsystem.view.DashboardView(role, userCitizenId);
            dashboard.setVisible(true);
            this.dispose();
        } else {
            // For admin role, return to CitizenEdit
            new CitizenEdit(role, userCitizenId).setVisible(true);
            this.dispose();
        }
    }

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = fileChooser.getSelectedFile();
            selectedImagePath = selectedFile.getAbsolutePath();
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(new javax.swing.ImageIcon(selectedImagePath).getImage().getScaledInstance(90, 90, java.awt.Image.SCALE_SMOOTH));
            ProfileImageLabel.setIcon(icon);
        }
    }

    private void setupDateFieldCalendar() {
        // Make date field clickable for calendar selection
        if (dateofbirth != null) {
            dateofbirth.setEditable(false);
            dateofbirth.setToolTipText("Click to select date");
            dateofbirth.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    openDatePicker();
                }
            });
        }
    }
    
    private void openDatePicker() {
        Date selectedDate = showCalendarDialog(dateofbirth.getText(), "Select Date of Birth");
        if (selectedDate != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dateofbirth.setText(sdf.format(selectedDate));
        }
    }
    
    private Date showCalendarDialog(String currentDate, String title) {
        // Parse current date
        Date initialDate = new Date();
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            if (currentDate != null && !currentDate.trim().isEmpty()) {
                initialDate = sdf.parse(currentDate);
            }
        } catch (Exception e) {
            // Use current date if parsing fails
            initialDate = new Date();
        }
        
        // Create calendar dialog
        javax.swing.JDialog calendarDialog = new javax.swing.JDialog(this, title, true);
        calendarDialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        calendarDialog.setLayout(new java.awt.BorderLayout());
        
        // Create calendar panel
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(initialDate);
        
        // Year spinner
        javax.swing.SpinnerModel yearModel = new javax.swing.SpinnerNumberModel(cal.get(java.util.Calendar.YEAR), 1900, 2100, 1);
        javax.swing.JSpinner yearSpinner = new javax.swing.JSpinner(yearModel);
        
        // Month combo box
        String[] months = {"January", "February", "March", "April", "May", "June",
                          "July", "August", "September", "October", "November", "December"};
        javax.swing.JComboBox<String> monthCombo = new javax.swing.JComboBox<>(months);
        monthCombo.setSelectedIndex(cal.get(java.util.Calendar.MONTH));
        
        // Day spinner
        javax.swing.SpinnerModel dayModel = new javax.swing.SpinnerNumberModel(cal.get(java.util.Calendar.DAY_OF_MONTH), 1, 31, 1);
        javax.swing.JSpinner daySpinner = new javax.swing.JSpinner(dayModel);
        
        // Update day spinner when month/year changes
        Runnable updateDaySpinner = () -> {
            int year = (Integer) yearSpinner.getValue();
            int month = monthCombo.getSelectedIndex();
            java.util.Calendar tempCal = java.util.Calendar.getInstance();
            tempCal.set(year, month, 1);
            int maxDay = tempCal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
            int currentDay = (Integer) daySpinner.getValue();
            if (currentDay > maxDay) {
                daySpinner.setValue(maxDay);
            }
            ((javax.swing.SpinnerNumberModel) daySpinner.getModel()).setMaximum(maxDay);
        };
        
        yearSpinner.addChangeListener(e -> updateDaySpinner.run());
        monthCombo.addActionListener(e -> updateDaySpinner.run());
        
        // Create top panel for date selection
        javax.swing.JPanel datePanel = new javax.swing.JPanel(new java.awt.GridBagLayout());
        datePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Date"));
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(5, 5, 5, 5);
        
        gbc.gridx = 0; gbc.gridy = 0;
        datePanel.add(new javax.swing.JLabel("Year:"), gbc);
        gbc.gridx = 1;
        datePanel.add(yearSpinner, gbc);
        
        gbc.gridx = 0; gbc.gridy = 1;
        datePanel.add(new javax.swing.JLabel("Month:"), gbc);
        gbc.gridx = 1;
        datePanel.add(monthCombo, gbc);
        
        gbc.gridx = 0; gbc.gridy = 2;
        datePanel.add(new javax.swing.JLabel("Day:"), gbc);
        gbc.gridx = 1;
        datePanel.add(daySpinner, gbc);
        
        // Create preview label
        javax.swing.JLabel previewLabel = new javax.swing.JLabel();
        previewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previewLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Date"));
        
        // Update preview
        Runnable updatePreview = () -> {
            try {
                int year = (Integer) yearSpinner.getValue();
                int month = monthCombo.getSelectedIndex();
                int day = (Integer) daySpinner.getValue();
                java.util.Calendar previewCal = java.util.Calendar.getInstance();
                previewCal.set(year, month, day);
                SimpleDateFormat displayFormat = new SimpleDateFormat("EEEE, MMMM dd, yyyy");
                previewLabel.setText(displayFormat.format(previewCal.getTime()));
            } catch (Exception e) {
                previewLabel.setText("Invalid Date");
            }
        };
        
        yearSpinner.addChangeListener(e -> updatePreview.run());
        monthCombo.addActionListener(e -> updatePreview.run());
        daySpinner.addChangeListener(e -> updatePreview.run());
        updatePreview.run(); // Initial update
        
        // Create button panel
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel(new java.awt.FlowLayout());
        javax.swing.JButton okButton = new javax.swing.JButton("OK");
        javax.swing.JButton cancelButton = new javax.swing.JButton("Cancel");
        javax.swing.JButton todayButton = new javax.swing.JButton("Today");
        
        final Date[] selectedDate = {null};
        
        okButton.addActionListener(e -> {
            try {
                int year = (Integer) yearSpinner.getValue();
                int month = monthCombo.getSelectedIndex();
                int day = (Integer) daySpinner.getValue();
                java.util.Calendar resultCal = java.util.Calendar.getInstance();
                resultCal.set(year, month, day);
                selectedDate[0] = resultCal.getTime();
                calendarDialog.dispose();
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(calendarDialog, "Please select a valid date!");
            }
        });
        
        cancelButton.addActionListener(e -> {
            selectedDate[0] = null;
            calendarDialog.dispose();
        });
        
        todayButton.addActionListener(e -> {
            java.util.Calendar today = java.util.Calendar.getInstance();
            yearSpinner.setValue(today.get(java.util.Calendar.YEAR));
            monthCombo.setSelectedIndex(today.get(java.util.Calendar.MONTH));
            daySpinner.setValue(today.get(java.util.Calendar.DAY_OF_MONTH));
        });
        
        buttonPanel.add(todayButton);
        buttonPanel.add(okButton);
        buttonPanel.add(cancelButton);
        
        // Assemble dialog
        calendarDialog.add(datePanel, java.awt.BorderLayout.NORTH);
        calendarDialog.add(previewLabel, java.awt.BorderLayout.CENTER);
        calendarDialog.add(buttonPanel, java.awt.BorderLayout.SOUTH);
        
        // Set dialog properties
        calendarDialog.setSize(300, 250);
        calendarDialog.setLocationRelativeTo(this);
        calendarDialog.setVisible(true);
        
        return selectedDate[0];
    }

}
