/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gaumanagementsystem.view;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author wangel
 */
public class RegisterView extends javax.swing.JFrame {

    public RegisterView() {
        initComponents();

        // Group the radio buttons so only one can be selected
        ButtonGroup roleGroup = new ButtonGroup();
        roleGroup.add(role_Admin);
        roleGroup.add(role_User);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        RegisterUser = new javax.swing.JButton();
        backtologin = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        backtologin2 = new javax.swing.JButton();
        view_password = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        Passwordlabel = new javax.swing.JLabel();
        Passwordlabel1 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        role_Admin = new javax.swing.JRadioButton();
        role_User = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Already have an account?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 384, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Role");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 116, -1));

        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 350, -1));

        RegisterUser.setBackground(new java.awt.Color(102, 102, 255));
        RegisterUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        RegisterUser.setForeground(new java.awt.Color(255, 255, 255));
        RegisterUser.setText("Register");
        RegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUserActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 381, -1, -1));

        backtologin.setBackground(new java.awt.Color(102, 102, 255));
        backtologin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backtologin.setForeground(new java.awt.Color(255, 255, 255));
        backtologin.setText("Back");
        backtologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinActionPerformed(evt);
            }
        });
        getContentPane().add(backtologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 381, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 116, -1));

        backtologin2.setBackground(new java.awt.Color(102, 102, 255));
        backtologin2.setForeground(new java.awt.Color(255, 255, 255));
        backtologin2.setText("Login");
        backtologin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologin2ActionPerformed(evt);
            }
        });
        getContentPane().add(backtologin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 381, -1, -1));

        view_password.setText("View Password");
        view_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(view_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 349, -1));

        Passwordlabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Passwordlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Passwordlabel.setText("Password");
        getContentPane().add(Passwordlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 117, 24));

        Passwordlabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Passwordlabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Passwordlabel1.setText("Confirm password");
        getContentPane().add(Passwordlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 117, 24));

        confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(confirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 349, -1));

        ButtonGroup.add(role_Admin);
        role_Admin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        role_Admin.setText("Admin");
        role_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_AdminActionPerformed(evt);
            }
        });
        getContentPane().add(role_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        ButtonGroup.add(role_User);
        role_User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        role_User.setText("User");
        getContentPane().add(role_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 98, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setText("Hamro Smart Gaun");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 255));
        Title.setText("Sign up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void RegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterUserActionPerformed

    private void view_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_passwordActionPerformed
        if (view_password.isSelected()) {
            // Show passwords
            password.setEchoChar('\u0000');  // Show password
            confirmpassword.setEchoChar('\u0000');  // Show confirm password
            view_password.setText("Hide Password");
        } else {
            // Hide passwords
            password.setEchoChar('•');  // Hide password
            confirmpassword.setEchoChar('•');  // Hide confirm password
            view_password.setText("View Password");
        }
    }//GEN-LAST:event_view_passwordActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void role_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role_AdminActionPerformed

    private void backtologin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologin2ActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView();  // Create an instance of LoginView
        login.setVisible(true);             // Show the LoginView
        this.dispose();                     // Close RegisterView (optional)
    }//GEN-LAST:event_backtologin2ActionPerformed

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView(); 
        login.setVisible(true);           
        this.dispose(); 
    }//GEN-LAST:event_backtologinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterView view = new RegisterView();
                gaumanagementsystem.controller.RegisterController controller = new gaumanagementsystem.controller.RegisterController(view);
                controller.open();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JLabel Passwordlabel;
    private javax.swing.JLabel Passwordlabel1;
    private javax.swing.JButton RegisterUser;
    private javax.swing.JLabel Title;
    private javax.swing.JButton backtologin;
    private javax.swing.JButton backtologin2;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton role_Admin;
    private javax.swing.JRadioButton role_User;
    private javax.swing.JCheckBox view_password;
    // End of variables declaration//GEN-END:variables

    
    public javax.swing.JTextField getEmailTextField(){
    return email;
    }
    
    public String getRadioButton() {
        if (role_Admin.isSelected()) {
           return "Admin";
        } else if (role_User.isSelected()) {
            return "User";
        } else {
            return "";
    }
    }
                                         
    
    public javax.swing.JPasswordField getPasswordField(){
    return password;
    }

    public javax.swing.JPasswordField getConfirmPasswordField(){
    return confirmpassword;
    }

    public void registerUser(ActionListener listener){
        RegisterUser.addActionListener(listener);
    }
    
    // Getter methods for controller access
    public javax.swing.JButton getRegisterUserButton() {
        return RegisterUser;
    }
    
    public javax.swing.JButton getBackToLoginButton() {
        return backtologin;
    }
    
    public javax.swing.JButton getLoginButton() {
        return backtologin2;
    }
    
    public javax.swing.JCheckBox getViewPasswordCheckBox() {
        return view_password;
    }
}