/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gaumanagementsystem.view;

import java.awt.event.ActionListener;
<<<<<<< HEAD
import gaumanagementsystem.controller.UserController;
import javax.swing.*;
import java.sql.*;
import gaumanagementsystem.database.MySqlConnection;
=======
import javax.swing.ButtonGroup;
>>>>>>> sambriddha

/**
 *
 * @author wangel
 */
public class RegisterView extends javax.swing.JFrame {

<<<<<<< HEAD
    private MySqlConnection dbConnection;

    /**
     * Creates new form RegistrationView
     */
    public RegisterView() {
        initComponents();
        dbConnection = new MySqlConnection();
        setLocationRelativeTo(null);
        setupInitialState();
    }

    private void setupInitialState() {
        // Set up initial password field state
        password.setEchoChar('•');
        confirmpassword.setEchoChar('•');
        
        // Set up the gotologin button action
        gotologin.addActionListener(e -> {
            LoginView loginView = new LoginView();
            loginView.setVisible(true);
            dispose();
        });
=======
    public RegisterView() {
        initComponents();

        // Group the radio buttons so only one can be selected
        ButtonGroup roleGroup = new ButtonGroup();
        roleGroup.add(role_Admin);
        roleGroup.add(role_User);
>>>>>>> sambriddha
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        backtologin = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        backtologin2 = new javax.swing.JButton();
        view_password = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        Passwordlabel = new javax.swing.JLabel();
        Passwordlabel1 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JPasswordField();
        role_Admin = new javax.swing.JRadioButton();
        role_User = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Already have an account?");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Hamro Smart Gaun");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Role");

        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 255));
        Title.setText("Sign up");

        registerButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Username");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        backtologin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        backtologin.setText("Back");
        backtologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        backtologin2.setText("Login");
        backtologin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologin2ActionPerformed(evt);
            }
        });

        view_password.setText("View Password");
        view_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_passwordActionPerformed(evt);
            }
        });

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        Passwordlabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Passwordlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Passwordlabel.setText("Password");

        Passwordlabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Passwordlabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Passwordlabel1.setText("Confirm password");

        confirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });

        ButtonGroup.add(role_Admin);
        role_Admin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        role_Admin.setText("Admin");
        role_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                role_AdminActionPerformed(evt);
            }
        });

        ButtonGroup.add(role_User);
        role_User.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        role_User.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(role_Admin)
                        .addGap(6, 6, 6)
                        .addComponent(role_User, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Passwordlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(view_password))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backtologin)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(backtologin2)
                        .addGap(106, 106, 106)
                        .addComponent(registerButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9))
                    .addComponent(role_Admin)
                    .addComponent(role_User))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwordlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(view_password)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backtologin)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(backtologin2)
                    .addComponent(registerButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {
        // No specific action needed
    }

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {
        // No specific action needed
    }

<<<<<<< HEAD
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {
        // No specific action needed
    }

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {
        UserController controller = new UserController();
        controller.handleRegistration(this);
    }

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {
        LoginView loginView = new LoginView();
        loginView.setVisible(true);
        dispose();
    }

    private void view_passwordActionPerformed(java.awt.event.ActionEvent evt) {
        if (view_password.isSelected()) {
            password.setEchoChar((char) 0);
            confirmpassword.setEchoChar((char) 0);
        } else {
            password.setEchoChar('•');
            confirmpassword.setEchoChar('•');
        }
    }
=======
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed

    private void view_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view_passwordActionPerformed
>>>>>>> sambriddha

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // No specific action needed
    }

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {
        // No specific action needed
    }

<<<<<<< HEAD
    private void genderActionPerformed(java.awt.event.ActionEvent evt) {
        // No specific action needed
    }
=======
    private void role_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_role_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_role_AdminActionPerformed

    private void backtologin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologin2ActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView();  // Create an instance of LoginView
        login.setVisible(true);             // Show the LoginView
        this.dispose();                     // Close RegisterView (optional)
    }//GEN-LAST:event_backtologin2ActionPerformed

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinActionPerformed
        // TODO add your handling code here:
        LoginView login = new LoginView(); 
        login.setVisible(true);           
        this.dispose(); 
    }//GEN-LAST:event_backtologinActionPerformed
>>>>>>> sambriddha

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JLabel Passwordlabel;
    private javax.swing.JLabel Passwordlabel1;
    private javax.swing.JLabel Title;
    private javax.swing.JButton backtologin;
    private javax.swing.JButton backtologin2;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerButton;
    private javax.swing.JRadioButton role_Admin;
    private javax.swing.JRadioButton role_User;
    private javax.swing.JTextField username;
    private javax.swing.JCheckBox view_password;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getUsernameTextField(){
    return username;
    }
    
    public javax.swing.JTextField getEmailTextField(){
    return email;
    }
    
    public String getRadioButton() {
        if (role_Admin.isSelected()) {
           return "Admin";
        } else if (role_User.isSelected()) {
            return "User";
        } else {
            return "";
    }
    }
                                         
    
    public javax.swing.JPasswordField getPasswordField(){
    return password;
    }

    public javax.swing.JPasswordField getConfirmPasswordField(){
    return confirmpassword;
    }

    
    //    to add action listener to the button
    public void registerUser(ActionListener listener){
        registerButton.addActionListener(listener);
    }
}